pipeline {
    agent any
    stages {
    stage('maven install') {
      steps {
         withMaven(maven: 'Maven3') {
          script {
                        bat 'start /B mvn clean install'
                    }
  }
      }
    }
  
  }
}
